### ISSUE TITLE
Add decoder documentation

### ISSUE THREAD

**Issue by fulldecent** [xpepermint/httlib-rs#2]
https://github.com/xpepermint/httlib-rs/blob/main/huffman/src/decode/reader.rs#L3

https://github.com/xpepermint/httlib-rs/blob/main/huffman/src/decode/reader.rs#L23

https://github.com/xpepermint/httlib-rs/blob/main/huffman/src/decode/reader.rs#L58

https://github.com/xpepermint/httlib-rs/blob/main/huffman/src/decode/reader.rs#L77

**Comment by xpepermint** [comment]
LOL :). True, these are my notes which will be removed once the blog for the decoder is ready. Please allow me to rename the issue :).

**Comment by xpepermint** [comment]
The documentation for the entire package has been updated. Now all modules and functions are extensively documented.
