### ISSUE TITLE
Feature parity: missing binary test case

### ISSUE THREAD

**Issue by fulldecent** [xpepermint/httlib-rs#3]
For feature parity with another implementation, a test case is missing where binary data is used.

https://github.com/hyperium/h2/blob/4398e169e87afa0daaf9f49c2f411e51096d5cd3/src/hpack/huffman/mod.rs#L201

**Comment by xpepermint** [comment]
https://github.com/xpepermint/httlib-rs/commit/feed48ae3a4d4c7025becdc756c0906566f00d00
