### ISSUE TITLE
Specification requirements are not tested

### ISSUE THREAD

**Issue by fulldecent** [xpepermint/httlib-rs#4]
In the specification, certain requirements are set for decoding errors.

https://httpwg.org/specs/rfc7541.html#string.literal.representation

> Upon decoding, an incomplete code at the end of the encoded data is to be considered as padding and discarded.

-- This is tested already. But test case documentation could be improved by including the above fact in text. (i.e. not every test case ends on a boundary.)

> A padding strictly longer than 7 bits MUST be treated as a decoding error.

-- TEST CASE MISSING

> A padding not corresponding to the most significant bits of the code for the EOS symbol MUST be treated as a decoding error.

-- TEST CASE MISSING

> A Huffman-encoded string literal containing the EOS symbol MUST be treated as a decoding error.

-- TEST CASE MISSING

**Comment by xpepermint** [comment]
Correct! You are referring to this paragraph from the spec:

> Upon decoding, an incomplete code at the end of the encoded data is to be considered as padding and discarded. A padding strictly longer than 7 bits MUST be treated as a decoding error. A padding not corresponding to the most significant bits of the code for the EOS symbol MUST be treated as a decoding error. A Huffman-encoded string literal containing the EOS symbol MUST be treated as a decoding error.

So what I understand is that when the last byte is read, the padding might or might not be included. It depends if the last character bits completed as a full octet or not. If the last character octet did not complete as octet, then EOS bits exist there as a padding to fill the full octet.

```
0 = DATA
X = PADDING
E = ERROR
00000000 0XXXXXXX EEEEEEEE
```

These claims could somehow be confirmed by this paragraph:

```
As the Huffman-encoded data doesn't always end at an octet boundary, some padding is inserted after it, up to the next octet boundary.  To prevent this padding from being misinterpreted as part of the string literal, the most significant bits of the code corresponding to the EOS (end-of-string) symbol are used.
```

Please correct me if I'm wrong. Everything regarding HTTP/2 spec gets super confusing when you start implementing their words.

**Comment by fulldecent** [comment]
Here is the test case to try:

`f1e3 c2e5 f23a 6ba0 ab90 f4ff`

-->

`www.example.com`

In the HPACK specification, test C.4.1.

So you can see that the full `111111111111111111111111111111` bits are not inside the encoded string.

**Comment by xpepermint** [comment]
This should be fixed: https://github.com/xpepermint/httlib-rs/commit/62d54a4e73f90c2e6d59f6ca7f8303d8050554a4

> Upon decoding, an incomplete code at the end of the encoded data is to be considered as padding and discarded.

This is now explicitly tested by the decoder itself: https://github.com/xpepermint/httlib-rs/blob/62d54a4e73f90c2e6d59f6ca7f8303d8050554a4/huffman/src/decode/reader.rs#L81

> A padding strictly longer than 7 bits MUST be treated as a decoding error.

Now also tested: https://github.com/xpepermint/httlib-rs/blob/62d54a4e73f90c2e6d59f6ca7f8303d8050554a4/huffman/src/decode/reader.rs#L87 https://github.com/xpepermint/httlib-rs/blob/62d54a4e73f90c2e6d59f6ca7f8303d8050554a4/huffman/src/decode/mod.rs#L393

> A padding not corresponding to the most significant bits of the code for the EOS symbol MUST be treated as a decoding error.

Tests added for invalid endings: https://github.com/xpepermint/httlib-rs/blob/62d54a4e73f90c2e6d59f6ca7f8303d8050554a4/huffman/src/decode/mod.rs#L389

> A Huffman-encoded string literal containing the EOS symbol MUST be treated as a decoding error.

Test added: https://github.com/xpepermint/httlib-rs/blob/62d54a4e73f90c2e6d59f6ca7f8303d8050554a4/huffman/src/decode/mod.rs#L397

@fulldecent I think this issue can now be closed but please do check again.
